import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ShoppingBag,Search,Menu,X,Heart,ArrowRight,Minus,Plus,ChevronLeft} from 'lucide-react';
import './styles.css';

const products=[
{id:1,name:'Sculpted Blazer',category:'Women',price:89,tag:'New',sizes:['XS','S','M','L'],colors:['Black','Stone'],image:'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?auto=format&fit=crop&w=900&q=85',desc:'A clean, structured blazer cut for an easy modern silhouette.'},
{id:2,name:'Essential Overshirt',category:'Men',price:64,tag:'Bestseller',sizes:['S','M','L','XL'],colors:['Black','Cream'],image:'https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?auto=format&fit=crop&w=900&q=85',desc:'A versatile overshirt with a relaxed profile and understated finish.'},
{id:3,name:'Velloura Court',category:'Shoes',price:78,tag:'New',sizes:['38','39','40','41','42','43'],colors:['White','Black'],image:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85',desc:'Minimal low-profile sneakers designed for daily rotation.'},
{id:4,name:'Minimal Carryall',category:'Accessories',price:55,tag:'Limited',sizes:['One Size'],colors:['Black','Tan'],image:'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=85',desc:'A refined everyday carryall with a spacious, uncluttered interior.'},
{id:5,name:'Fluid Midi Dress',category:'Women',price:72,tag:'New',sizes:['XS','S','M','L'],colors:['Espresso','Black'],image:'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=900&q=85',desc:'A fluid midi silhouette balancing softness with a precise neckline.'},
{id:6,name:'Relaxed Trouser',category:'Men',price:58,tag:'Core',sizes:['28','30','32','34','36'],colors:['Charcoal','Stone'],image:'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=900&q=85',desc:'Straight relaxed trousers designed to work across smart and casual wardrobes.'}
];
const money=n=>'$'+n.toFixed(2);
function App(){
 const [menu,setMenu]=useState(false),[query,setQuery]=useState(''),[category,setCategory]=useState('All');
 const [selected,setSelected]=useState(null),[cartOpen,setCartOpen]=useState(false),[checkout,setCheckout]=useState(false);
 const [cart,setCart]=useState(()=>{try{return JSON.parse(localStorage.getItem('velloura-cart'))||[]}catch{return[]}});
 const [order,setOrder]=useState(null);
 useEffect(()=>localStorage.setItem('velloura-cart',JSON.stringify(cart)),[cart]);
 const visible=useMemo(()=>products.filter(p=>(category==='All'||p.category===category)&&(p.name+' '+p.category).toLowerCase().includes(query.toLowerCase())),[query,category]);
 const count=cart.reduce((a,x)=>a+x.qty,0), subtotal=cart.reduce((a,x)=>a+x.price*x.qty,0);
 const add=(p,size,color)=>{setCart(c=>{const i=c.findIndex(x=>x.id===p.id&&x.size===size&&x.color===color);if(i<0)return[...c,{...p,size,color,qty:1}];return c.map((x,j)=>j===i?{...x,qty:x.qty+1}:x)});setCartOpen(true)};
 const qty=(i,d)=>setCart(c=>c.map((x,j)=>j===i?{...x,qty:x.qty+d}:x).filter(x=>x.qty>0));
 const submit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const ref='VEL-'+Date.now().toString().slice(-7);const record={ref,data,items:cart,total:subtotal,status:'Order received',createdAt:new Date().toISOString()};localStorage.setItem('velloura-last-order',JSON.stringify(record));setOrder(record);setCart([]);setCheckout(false)};
 return <div>
 <div className="announcement">COMPLIMENTARY DELIVERY ON ORDERS OVER $100</div>
 <header><button className="icon mobile" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><a className="logo" href="#" onClick={()=>setSelected(null)}>VELLOURA</a>
 <nav className={menu?'open':''}>{['Women','Men','Shoes','Accessories'].map(x=><a href="#shop" key={x} onClick={()=>{setCategory(x);setMenu(false);setSelected(null)}}>{x}</a>)}</nav>
 <div className="actions"><div className="search"><Search size={18}/><input aria-label="Search" placeholder="Search" value={query} onChange={e=>setQuery(e.target.value)}/></div><button className="icon bag" onClick={()=>setCartOpen(true)}><ShoppingBag/><span>{count}</span></button></div></header>
 {order&&<div className="success"><button onClick={()=>setOrder(null)}><X/></button><p className="eyebrow">ORDER RECEIVED</p><h2>Thank you.</h2><p>Reference <b>{order.ref}</b>. Your order has been saved on this device. Online payment and server-side order processing will be connected before launch.</p></div>}
 {selected?<Product p={selected} back={()=>setSelected(null)} add={add}/>:<main>
 <section className="hero"><div className="hero-copy"><p className="eyebrow">THE NEW COLLECTION</p><h1>Quiet confidence.<br/>Distinctly Velloura.</h1><p>Modern silhouettes, considered details and everyday pieces designed to stay in rotation.</p><a className="primary" href="#shop">SHOP THE COLLECTION <ArrowRight size={18}/></a></div></section>
 <section className="categories">{['Women','Men','Shoes'].map(x=><a href="#shop" key={x} onClick={()=>setCategory(x)} className={'cat '+x.toLowerCase()}><span>{x.toUpperCase()}</span></a>)}</section>
 <section className="shop" id="shop"><div className="section-head"><div><p className="eyebrow">CURATED NOW</p><h2>{category==='All'?'New arrivals':category}</h2></div><div className="filters">{['All','Women','Men','Shoes','Accessories'].map(x=><button className={category===x?'active':''} onClick={()=>setCategory(x)} key={x}>{x}</button>)}</div></div>
 <div className="mobile-search"><Search size={18}/><input placeholder="Search Velloura" value={query} onChange={e=>setQuery(e.target.value)}/></div>
 <div className="grid">{visible.map(p=><article className="product" key={p.id}><button className="photo" onClick={()=>setSelected(p)}><img src={p.image} alt={p.name}/><span className="tag">{p.tag}</span><span className="heart"><Heart size={20}/></span></button><div className="product-info"><div><p className="category">{p.category}</p><h3>{p.name}</h3><p>{money(p.price)}</p></div><button onClick={()=>setSelected(p)}>VIEW</button></div></article>)}</div>{!visible.length&&<p className="empty">No products match your search.</p>}</section>
 <section className="statement"><p className="eyebrow">VELLOURA</p><h2>Less noise.<br/>Better pieces.</h2><p>A considered wardrobe built around versatility, form and confident simplicity.</p></section></main>}
 <footer><a className="logo light" href="#">VELLOURA</a><div><p>SHOP</p><a href="#shop">New arrivals</a><a href="#shop">Clothing</a><a href="#shop">Shoes</a></div><div><p>HELP</p><a href="#">Delivery & returns</a><a href="#">Size guide</a><a href="#">Contact</a></div><div className="newsletter"><p>PRIVATE LIST</p><h3>First access, no noise.</h3><div><input placeholder="Email address"/><button>JOIN</button></div></div><small>© 2026 Velloura. All rights reserved.</small></footer>
 {cartOpen&&<><div className="shade" onClick={()=>setCartOpen(false)}/><aside className="cart"><div className="cart-title"><h2>Your bag</h2><button onClick={()=>setCartOpen(false)}><X/></button></div>{!cart.length?<p className="empty">Your bag is empty.</p>:<>{cart.map((x,i)=><div className="cart-row" key={i}><img src={x.image} alt=""/><div><h3>{x.name}</h3><p>{x.color} / {x.size}</p><p>{money(x.price)}</p><div className="stepper"><button onClick={()=>qty(i,-1)}><Minus size={14}/></button><span>{x.qty}</span><button onClick={()=>qty(i,1)}><Plus size={14}/></button></div></div></div>)}<div className="cart-total"><span>Subtotal</span><b>{money(subtotal)}</b></div><button className="checkout-btn" onClick={()=>{setCartOpen(false);setCheckout(true)}}>CHECKOUT</button></>}</aside></>}
 {checkout&&<Checkout total={subtotal} close={()=>setCheckout(false)} submit={submit}/>}
 </div>
}
function Product({p,back,add}){const[size,setSize]=useState(p.sizes[0]),[color,setColor]=useState(p.colors[0]);return <main className="detail"><button className="back" onClick={back}><ChevronLeft size={17}/> BACK TO SHOP</button><div className="detail-grid"><div className="detail-photo"><img src={p.image} alt={p.name}/></div><div className="detail-copy"><p className="eyebrow">{p.category}</p><h1>{p.name}</h1><p className="detail-price">{money(p.price)}</p><p className="description">{p.desc}</p><label>COLOUR — {color}</label><div className="choices">{p.colors.map(x=><button key={x} className={x===color?'chosen':''} onClick={()=>setColor(x)}>{x}</button>)}</div><label>SIZE — {size}</label><div className="choices">{p.sizes.map(x=><button key={x} className={x===size?'chosen':''} onClick={()=>setSize(x)}>{x}</button>)}</div><button className="checkout-btn" onClick={()=>add(p,size,color)}>ADD TO BAG</button><div className="notes"><p>Complimentary delivery over $100</p><p>Returns policy will be finalized before launch</p></div></div></div></main>}
function Checkout({total,close,submit}){return <div className="checkout-page"><button className="back" onClick={close}><ChevronLeft size={17}/> RETURN TO BAG</button><div className="checkout-wrap"><div><p className="eyebrow">SECURE CHECKOUT</p><h1>Delivery details</h1><p>Payment integration is intentionally disabled until the merchant payment provider is selected.</p></div><form onSubmit={submit}><div className="two"><input name="firstName" required placeholder="First name"/><input name="lastName" required placeholder="Last name"/></div><input name="email" type="email" required placeholder="Email"/><input name="phone" required placeholder="Phone"/><input name="address" required placeholder="Delivery address"/><div className="two"><input name="city" required placeholder="City"/><input name="country" value="Zimbabwe" readOnly/></div><div className="cart-total"><span>Order total</span><b>{money(total)}</b></div><button className="checkout-btn">PLACE ORDER</button><small>No payment will be taken in this development build.</small></form></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
